[package]
name        = "is_prime"
version     = "1.0.5"
authors     = ["Alfie John <alfie@alfie.wtf>"]
description = "Fast arbitrary length prime number checker using the Miller-Rabin primality test algorithm"

[dependencies]
ramp = "0.5.6"
